[package]
name = "win_hv"
description = "Demo client for a UEFI environment"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
publish.workspace = true

# no_std cannot support `cargo test` and `cargo bench`
[lib]
crate-type = ["cdylib"]
test = false
bench = false

[dependencies]
hv = { path = "../../hvcore" }
wdk = "0.2"
wdk-alloc = "0.2"
wdk-sys = "0.2"

[build-dependencies]
wdk-build = "0.2"

[lints]
workspace = true
