[package]
name = "win_hv"
version = "0.1.0"
license.workspace = true
publish.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]
test = false
bench = false

[dependencies]
hv = { path = "../../hvcore" }
wdk = "0.2"
wdk-alloc = "0.2"
wdk-sys = "0.2"

[build-dependencies]
wdk-build = "0.2"

[lints]
workspace = true
